/**
 * SystemDesignPanel - System design (SDLC Step 2)
 */

import React, { useState } from 'react';
import type { Stage } from '../App';

interface SystemDesignPanelProps {
  api: any;
  workspacePath: string | null;
  currentProject: { id: string; name: string; description: string; stage: Stage } | null;
  setCurrentProject: (project: any) => void;
  addNotification: (type: any, title: string, message: string) => void;
}

export function SystemDesignPanel({ currentProject, addNotification }: SystemDesignPanelProps) {
  const [components, setComponents] = useState<string[]>([]);
  const [newComponent, setNewComponent] = useState('');
  const [architecture, setArchitecture] = useState('');
  const [techStack, setTechStack] = useState<string[]>(['TypeScript', 'Node.js']);
  
  const addComponent = () => {
    if (newComponent.trim()) {
      setComponents([...components, newComponent]);
      setNewComponent('');
    }
  };
  
  const useAI = () => {
    addNotification('info', 'AI Design', 'Generating system design...');
  };
  
  return (
    <div className="system-design-panel">
      <div className="panel-header">
        <h2>System Design</h2>
        <p className="subtitle">Design your system architecture</p>
      </div>
      
      <div className="design-content">
        <div className="section">
          <h3>Architecture Overview</h3>
          <textarea
            value={architecture}
            onChange={e => setArchitecture(e.target.value)}
            placeholder="Describe the overall system architecture, components, and data flow..."
            rows={6}
          />
          <button className="ai-btn" onClick={useAI}>
            <span>🤖</span> Generate with AI
          </button>
        </div>
        
        <div className="section">
          <h3>System Components</h3>
          <div className="component-input">
            <input
              type="text"
              value={newComponent}
              onChange={e => setNewComponent(e.target.value)}
              onKeyDown={e => e.key === 'Enter' && addComponent()}
              placeholder="Add component (e.g., Auth Service, Database, API Gateway)..."
            />
            <button onClick={addComponent}>+</button>
          </div>
          <div className="component-grid">
            {components.map((comp, i) => (
              <div key={i} className="component-card">
                <span className="comp-icon">🧩</span>
                <span>{comp}</span>
                <button onClick={() => setComponents(c => c.filter((_, idx) => idx !== i))}>×</button>
              </div>
            ))}
            {components.length === 0 && (
              <p className="empty-text">Add system components</p>
            )}
          </div>
        </div>
        
        <div className="section">
          <h3>Technology Stack</h3>
          <div className="tech-chips">
            {techStack.map((tech, i) => (
              <span key={i} className="tech-chip">
                {tech}
                <button onClick={() => setTechStack(t => t.filter((_, idx) => idx !== i))}>×</button>
              </span>
            ))}
            <input
              type="text"
              placeholder="+ Add"
              onKeyDown={e => {
                if (e.key === 'Enter' && e.currentTarget.value.trim()) {
                  setTechStack([...techStack, e.currentTarget.value.trim()]);
                  e.currentTarget.value = '';
                }
              }}
            />
          </div>
        </div>
        
        <div className="section">
          <h3>Data Flow</h3>
          <div className="diagram-placeholder">
            <span>📊</span>
            <p>Data flow diagram will be generated by AI</p>
          </div>
        </div>
        
        <button className="save-btn">Save System Design</button>
      </div>
      
      <style>{`
        .system-design-panel {
          display: flex;
          flex-direction: column;
          height: 100%;
          padding: 24px;
          overflow-y: auto;
        }
        
        .panel-header h2 { font-size: 24px; margin-bottom: 8px; }
        .subtitle { color: var(--color-text-secondary); margin-bottom: 24px; }
        
        .design-content { display: flex; flex-direction: column; gap: 24px; max-width: 900px; }
        .section h3 { font-size: 16px; margin-bottom: 12px; }
        
        .section textarea { width: 100%; margin-bottom: 12px; }
        
        .ai-btn {
          display: flex; align-items: center; justify-content: center; gap: 8px;
          padding: 10px; background: var(--color-bg-tertiary); border-radius: var(--radius-md);
        }
        .ai-btn:hover { background: var(--color-accent); color: white; }
        
        .component-input { display: flex; gap: 8px; margin-bottom: 12px; }
        .component-input input { flex: 1; }
        .component-input button { padding: 8px 16px; background: var(--color-accent); color: white; border-radius: var(--radius-md); }
        
        .component-grid { display: flex; flex-wrap: wrap; gap: 8px; }
        .component-card {
          display: flex; align-items: center; gap: 8px; padding: 8px 12px;
          background: var(--color-bg-secondary); border-radius: var(--radius-md);
        }
        .component-card button { color: var(--color-text-muted); }
        
        .tech-chips { display: flex; flex-wrap: wrap; gap: 8px; align-items: center; }
        .tech-chip {
          display: flex; align-items: center; gap: 6px; padding: 6px 12px;
          background: var(--color-accent); color: white; border-radius: var(--radius-sm);
          font-size: 12px;
        }
        .tech-chip button { color: rgba(255,255,255,0.7); }
        
        .diagram-placeholder {
          display: flex; flex-direction: column; align-items: center; justify-content: center;
          height: 200px; background: var(--color-bg-secondary); border-radius: var(--radius-lg);
          border: 2px dashed var(--color-border);
        }
        .diagram-placeholder span { font-size: 48px; margin-bottom: 12px; }
        .diagram-placeholder p { color: var(--color-text-muted); }
        
        .empty-text { color: var(--color-text-muted); font-size: 13px; padding: 16px; }
        
        .save-btn { padding: 14px; background: var(--color-accent); color: white; border-radius: var(--radius-md); font-weight: 600; }
      `}</style>
    </div>
  );
}